services:
  app:
    build:
      context: .
      dockerfile: container/snaarf-app.dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    networks:
      - snaarf-network

  test:
    build:
      context: .
      dockerfile: container/snaarf-app.dockerfile
    command: pytest tests/ -v
    environment:
      - PYTHONWARNINGS=ignore::DeprecationWarning:werkzeug.*
      - DB_URI=postgresql://snaarf_app:${DB_PASS}@postgres:5432/snaarf_app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_AUTH_PASSWORD=${REDIS_AUTH_PASSWORD}
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_SECRET=${TWITCH_SECRET}
      - TWITCH_REDIRECT_URI=${TWITCH_REDIRECT_URI}
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    profiles:
      - test
    networks:
      - snaarf-network

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=snaarf_app
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=snaarf_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - snaarf-network

  redis:
    image: redis:7
    command: redis-server --requirepass ${REDIS_AUTH_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - snaarf-network

networks:
  snaarf-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
